version: 2
updates:
  # Maintain dependencies for Gradle
  - package-ecosystem: "gradle"
    directory: "/" # Location of build.gradle files
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of workflow files
    schedule:
      interval: "weekly"
